// <auto-generated />
using System;
using Bomberjam.Website.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bomberjam.Website.Migrations
{
    [DbContext(typeof(BomberjamContext))]
    [Migration("20210212233923_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Bomberjam.Website.Database.DbGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GameDuration")
                        .HasColumnType("REAL");

                    b.Property<double?>("InitDuration")
                        .HasColumnType("REAL");

                    b.Property<string>("Stderr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stdout")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbGameUser", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<float>("DeltaPoints")
                        .HasColumnType("REAL");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameUsers");
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbQueuedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20cba268-24e7-47f5-804f-0a8948de9864"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(7110),
                            Data = "00000000-0000-0000-0000-000000000001",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(7295),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("8b288526-d5b9-436d-aae1-67b08b9547e8"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8330),
                            Data = "00000000-0000-0000-0000-000000000002",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8331),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a2787561-fbdc-4ec1-bc0e-7fd75cd20c13"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8336),
                            Data = "00000000-0000-0000-0000-000000000003",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8336),
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("913a7188-5703-47e2-8902-e36a7bd833d9"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8339),
                            Data = "00000000-0000-0000-0000-000000000004",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8340),
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("c1678711-d2d8-4fa9-8553-eace62bb6e1b"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8342),
                            Data = "00000000-0000-0000-0000-000000000005",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8343),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("91b7226b-6cce-488c-9898-747b8408a5bc"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8346),
                            Data = "00000000-0000-0000-0000-000000000006",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8346),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("bc70f866-70df-41c5-b21f-67d7b7634f37"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8349),
                            Data = "00000000-0000-0000-0000-000000000007",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 965, DateTimeKind.Utc).AddTicks(8350),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("4aecc989-9e3e-49b7-bfab-32cb0230dab8"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(2331),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000003:Xenure",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(2333)
                        },
                        new
                        {
                            Id = new Guid("5ff16427-0feb-49dd-a4ab-3d4337d5423b"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4119),
                            Data = "00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4122)
                        },
                        new
                        {
                            Id = new Guid("05a9e2ab-ef26-46e8-99ca-26a0d0398523"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4169),
                            Data = "00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4170)
                        },
                        new
                        {
                            Id = new Guid("e24a1bb0-6dc5-45ab-b30e-97c68d4c1189"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4201),
                            Data = "00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000006:Pandarf",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4202)
                        },
                        new
                        {
                            Id = new Guid("0cb01ff3-a5cd-4e5f-80fd-58eca73cda61"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4271),
                            Data = "00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4272)
                        },
                        new
                        {
                            Id = new Guid("4e5cb5c6-4cc4-4ad7-9b97-b17752e143c6"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4344),
                            Data = "00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4345)
                        },
                        new
                        {
                            Id = new Guid("5eced64e-22d1-41c2-ab49-a08d4b25a060"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4375),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4376)
                        },
                        new
                        {
                            Id = new Guid("a2aa5c14-ba6d-4ab2-82aa-755b03af7010"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4464),
                            Data = "00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4465)
                        },
                        new
                        {
                            Id = new Guid("5e1fc41d-a1f3-4914-83d4-6de2dc41a70e"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4500),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4501)
                        },
                        new
                        {
                            Id = new Guid("d8fe2a7f-e079-4c86-9036-cbe62317905d"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4576),
                            Data = "00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4577)
                        },
                        new
                        {
                            Id = new Guid("931d8660-ec5b-4956-9542-19aef0050e69"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4610),
                            Data = "00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000003:Xenure",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4611)
                        },
                        new
                        {
                            Id = new Guid("2752f5d0-0579-4e59-ab3d-d246f6928149"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4640),
                            Data = "00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000003:Xenure",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4641)
                        },
                        new
                        {
                            Id = new Guid("7cc2c16c-d223-47e4-8fbf-2312368fa6ff"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4693),
                            Data = "00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4694)
                        },
                        new
                        {
                            Id = new Guid("30db36be-6790-422d-be99-50d1bc669ee3"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4723),
                            Data = "00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4724)
                        },
                        new
                        {
                            Id = new Guid("119d0fdf-481c-41fc-9d18-2ec59366956b"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4753),
                            Data = "00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000006:Pandarf",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4754)
                        },
                        new
                        {
                            Id = new Guid("02444894-d838-4952-a969-0a85dada15eb"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4816),
                            Data = "00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000003:Xenure",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4817)
                        },
                        new
                        {
                            Id = new Guid("96f2a857-8085-4d6b-a49a-192458fc2447"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4850),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000007:Mire",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4851)
                        },
                        new
                        {
                            Id = new Guid("219d68f1-cde4-4fc6-86fa-d407df6750de"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4880),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000007:Mire",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4881)
                        },
                        new
                        {
                            Id = new Guid("6a1fda96-8773-4487-aedd-eff01d4c4fa8"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4910),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000001:Askaiser",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4911)
                        },
                        new
                        {
                            Id = new Guid("78f59c57-03c1-4d9e-b83e-092a5834b5e5"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4940),
                            Data = "00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000001:Askaiser",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(4941)
                        },
                        new
                        {
                            Id = new Guid("e8fe6621-f5f9-4e05-b2ea-692c665865d2"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5001),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000006:Pandarf",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5002)
                        },
                        new
                        {
                            Id = new Guid("025be423-7916-4159-8167-39c0bd0423db"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5031),
                            Data = "00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5032)
                        },
                        new
                        {
                            Id = new Guid("87fb315c-718b-4fae-ae90-dcfa4c95b56d"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5061),
                            Data = "00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5062)
                        },
                        new
                        {
                            Id = new Guid("ea812db3-9f19-4d6a-9da5-373d577e59d7"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5091),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000004:Minty",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5092)
                        },
                        new
                        {
                            Id = new Guid("ff665674-1dff-4270-be05-76baeacd65f2"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5124),
                            Data = "00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5125)
                        },
                        new
                        {
                            Id = new Guid("fafad927-9753-4739-88de-e94d56a0fb09"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5154),
                            Data = "00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5155)
                        },
                        new
                        {
                            Id = new Guid("26eb0078-51e9-41d5-8b31-a50501156646"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5224),
                            Data = "00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000003:Xenure",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5225)
                        },
                        new
                        {
                            Id = new Guid("50a80a23-1012-4de3-b44b-f26825fd61b7"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5254),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5255)
                        },
                        new
                        {
                            Id = new Guid("d55b04e9-d733-4547-bb38-b22b423dc3fe"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5284),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5285)
                        },
                        new
                        {
                            Id = new Guid("1a2ecf25-4fea-42bd-9232-5dad00083040"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5313),
                            Data = "00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000006:Pandarf",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5314)
                        },
                        new
                        {
                            Id = new Guid("0a7356e9-af39-40d9-adff-19c87e7d2db8"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5343),
                            Data = "00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5344)
                        },
                        new
                        {
                            Id = new Guid("60be299d-80ee-40c5-8de7-85809d12059d"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5401),
                            Data = "00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000007:Mire",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5402)
                        },
                        new
                        {
                            Id = new Guid("3343d212-51e8-4916-8ec2-aef737a2decc"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5433),
                            Data = "00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5434)
                        },
                        new
                        {
                            Id = new Guid("82559707-bdaa-4dc6-90bc-9c23b736ec37"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5463),
                            Data = "00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000004:Minty",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5464)
                        },
                        new
                        {
                            Id = new Guid("0c4a5b42-330c-4d6c-8254-a106aa1102c8"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5492),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000007:Mire",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5493)
                        },
                        new
                        {
                            Id = new Guid("4517fb8d-0fa8-4622-99ca-ab938a9af665"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5522),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000003:Xenure",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5523)
                        },
                        new
                        {
                            Id = new Guid("fc9a0977-bcad-48e8-952d-342cac2b2136"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5582),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5583)
                        },
                        new
                        {
                            Id = new Guid("8feaabc6-4674-4862-a80f-78842769f58a"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5612),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000001:Askaiser",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5613)
                        },
                        new
                        {
                            Id = new Guid("3811824b-5171-4a25-84f7-13ca00304170"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5642),
                            Data = "00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000003:Xenure",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5642)
                        },
                        new
                        {
                            Id = new Guid("11d1087f-e45f-4b34-9258-859bfdeb5699"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5671),
                            Data = "00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000001:Askaiser",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5672)
                        },
                        new
                        {
                            Id = new Guid("752d9b0a-a95a-47e5-b3bd-6ffe2f4bb71b"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5703),
                            Data = "00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000006:Pandarf",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5704)
                        },
                        new
                        {
                            Id = new Guid("27041e4b-d843-4931-b9ae-a2bedbac649f"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5733),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000001:Askaiser",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5734)
                        },
                        new
                        {
                            Id = new Guid("a0fae483-e7ee-4c58-8628-d90a4f5b10df"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5793),
                            Data = "00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5794)
                        },
                        new
                        {
                            Id = new Guid("6cae45f4-d7b7-4913-9f3b-76a6cac6a104"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5823),
                            Data = "00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5823)
                        },
                        new
                        {
                            Id = new Guid("adcffcc7-466c-406f-bae5-634e7c42705e"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5852),
                            Data = "00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5853)
                        },
                        new
                        {
                            Id = new Guid("8f7def3c-4005-4a8b-b69a-c199e8d552ef"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5882),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5883)
                        },
                        new
                        {
                            Id = new Guid("7ae497b6-3b2d-4f1c-ad1d-0044a890ed18"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5912),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000001:Askaiser",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5912)
                        },
                        new
                        {
                            Id = new Guid("359acd8a-f0c4-458a-85fa-bc121c656b2e"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5973),
                            Data = "00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000007:Mire",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(5974)
                        },
                        new
                        {
                            Id = new Guid("a696c671-d34e-4512-96ee-490d86428063"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(6005),
                            Data = "00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000007:Mire",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(6006)
                        },
                        new
                        {
                            Id = new Guid("87a0bd9b-2eaa-441c-890f-04fb575d7fd1"),
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(6035),
                            Data = "00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 966, DateTimeKind.Utc).AddTicks(6036)
                        });
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BotLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompilationErrors")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GithubId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompiled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompiling")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Points")
                        .HasColumnType("REAL");

                    b.Property<int>("SubmitCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GithubId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(6549),
                            Email = "simmon.anthony@gmail.com",
                            GameCount = 0,
                            GithubId = 14242083,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(6727),
                            UserName = "Askaiser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8133),
                            Email = "falgar@gmail.com",
                            GameCount = 0,
                            GithubId = 36072624,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8135),
                            UserName = "Falgar"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8137),
                            Email = "xenure@gmail.com",
                            GameCount = 0,
                            GithubId = 9208753,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8138),
                            UserName = "Xenure"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8139),
                            Email = "minty@gmail.com",
                            GameCount = 0,
                            GithubId = 26142591,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8140),
                            UserName = "Minty"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8142),
                            Email = "kalmera@gmail.com",
                            GameCount = 0,
                            GithubId = 5122918,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8142),
                            UserName = "Kalmera"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8144),
                            Email = "pandarf@gmail.com",
                            GameCount = 0,
                            GithubId = 1035273,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8145),
                            UserName = "Pandarf"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8146),
                            Email = "mire@gmail.com",
                            GameCount = 0,
                            GithubId = 5489330,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 39, 22, 964, DateTimeKind.Utc).AddTicks(8147),
                            UserName = "Mire"
                        });
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbGameUser", b =>
                {
                    b.HasOne("Bomberjam.Website.Database.DbGame", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bomberjam.Website.Database.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbQueuedTask", b =>
                {
                    b.HasOne("Bomberjam.Website.Database.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
