// <auto-generated />
using System;
using Bomberjam.Website.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bomberjam.Website.Migrations
{
    [DbContext(typeof(BomberjamContext))]
    [Migration("20210212232459_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Bomberjam.Website.Database.DbGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GameDuration")
                        .HasColumnType("REAL");

                    b.Property<double?>("InitDuration")
                        .HasColumnType("REAL");

                    b.Property<string>("Stderr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stdout")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbGameUser", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<float>("DeltaPoints")
                        .HasColumnType("REAL");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameUsers");
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbQueuedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9d937cf-63cb-44dd-a3d1-895a128c3949"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(1205),
                            Data = "00000000-0000-0000-0000-000000000001",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(1458),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b996195a-3772-49e2-a1a1-480acf6d149f"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3632),
                            Data = "00000000-0000-0000-0000-000000000002",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3635),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a3c8af6d-aa68-4b22-8e63-331a36ec6a8e"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3641),
                            Data = "00000000-0000-0000-0000-000000000003",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3641),
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("fd4d90ae-420e-41de-87c0-2ac8cd01970a"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3644),
                            Data = "00000000-0000-0000-0000-000000000004",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3644),
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("f9983658-0d33-4f0c-b915-6be4daad3bfd"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3646),
                            Data = "00000000-0000-0000-0000-000000000005",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3647),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("c7bdf232-c8d8-4567-9f96-a2eb13fd5bcb"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3649),
                            Data = "00000000-0000-0000-0000-000000000006",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3650),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("ccbf6e0b-7309-456e-90c7-f796876efc31"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3652),
                            Data = "00000000-0000-0000-0000-000000000007",
                            Status = 1,
                            Type = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(3653),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("cada3406-dc2a-4a40-a6e4-015a20fa6bd4"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(8972),
                            Data = "00000000-0000-0000-0000-000000000002:Falgar,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000003:Xenure",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 832, DateTimeKind.Utc).AddTicks(8976)
                        },
                        new
                        {
                            Id = new Guid("1a52d853-319c-483b-a1d6-f043a0a38a84"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 833, DateTimeKind.Utc).AddTicks(1172),
                            Data = "00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000007:Mire,00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000005:Kalmera",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 833, DateTimeKind.Utc).AddTicks(1175)
                        },
                        new
                        {
                            Id = new Guid("8a91e879-64b7-4a07-9c03-db142d0c8aac"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 833, DateTimeKind.Utc).AddTicks(1222),
                            Data = "00000000-0000-0000-0000-000000000006:Pandarf,00000000-0000-0000-0000-000000000004:Minty,00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000002:Falgar",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 833, DateTimeKind.Utc).AddTicks(1223)
                        },
                        new
                        {
                            Id = new Guid("910a5286-4f6f-405a-8d34-09aabf1d759e"),
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 833, DateTimeKind.Utc).AddTicks(1249),
                            Data = "00000000-0000-0000-0000-000000000001:Askaiser,00000000-0000-0000-0000-000000000003:Xenure,00000000-0000-0000-0000-000000000005:Kalmera,00000000-0000-0000-0000-000000000006:Pandarf",
                            Status = 1,
                            Type = 2,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 833, DateTimeKind.Utc).AddTicks(1250)
                        });
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BotLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompilationErrors")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GithubId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompiled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompiling")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Points")
                        .HasColumnType("REAL");

                    b.Property<int>("SubmitCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GithubId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 830, DateTimeKind.Utc).AddTicks(9448),
                            Email = "simmon.anthony@gmail.com",
                            GameCount = 0,
                            GithubId = 14242083,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 830, DateTimeKind.Utc).AddTicks(9686),
                            UserName = "Askaiser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1380),
                            Email = "falgar@gmail.com",
                            GameCount = 0,
                            GithubId = 36072624,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1382),
                            UserName = "Falgar"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1385),
                            Email = "xenure@gmail.com",
                            GameCount = 0,
                            GithubId = 9208753,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1386),
                            UserName = "Xenure"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1387),
                            Email = "minty@gmail.com",
                            GameCount = 0,
                            GithubId = 26142591,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1388),
                            UserName = "Minty"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1389),
                            Email = "kalmera@gmail.com",
                            GameCount = 0,
                            GithubId = 5122918,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1390),
                            UserName = "Kalmera"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1391),
                            Email = "pandarf@gmail.com",
                            GameCount = 0,
                            GithubId = 1035273,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1392),
                            UserName = "Pandarf"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            BotLanguage = "",
                            CompilationErrors = "",
                            Created = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1393),
                            Email = "mire@gmail.com",
                            GameCount = 0,
                            GithubId = 5489330,
                            IsCompiled = false,
                            IsCompiling = false,
                            Points = 1500f,
                            SubmitCount = 1,
                            Updated = new DateTime(2021, 2, 12, 23, 24, 58, 831, DateTimeKind.Utc).AddTicks(1394),
                            UserName = "Mire"
                        });
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbGameUser", b =>
                {
                    b.HasOne("Bomberjam.Website.Database.DbGame", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bomberjam.Website.Database.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bomberjam.Website.Database.DbQueuedTask", b =>
                {
                    b.HasOne("Bomberjam.Website.Database.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
