name: Worker Docker build CI

on:
  push:
    branches: [ master ]
    paths:
      - 'common/**/*'
      - 'engine/**/*'
      - 'worker/**/*'
      - 'worker.Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'common/**/*'
      - 'engine/**/*'
      - 'worker/**/*'
      - 'worker.Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the worker Docker image
      run: docker build . --no-cache --file worker.Dockerfile --tag bomberjam-worker:$(date +%s)
